language: go
go:
  - "1.11"
  - "1.12"
  - "1.13"

install: make install-deps
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: 
  - go test -cover -coverprofile=cover.out github.com/jordyv/prometheus-p1-exporter/conn github.com/jordyv/prometheus-p1-exporter/parser
after_script:
  - ./cc-test-reporter format-coverage cover.out --input-type gocov
  - ./cc-test-reporter upload-coverage
