
[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/go-serial"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"
